project:
  type: website

website:
  title: "5000 Homework 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About me
      - href: Data Science Topic.ipynb
        text: Introduction

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



