project:
  type: website

website:
  title: "Stock Price Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About me
      - href: code.ipynb
        text: Code
      - href: data.ipynb
        text: Data
      - href: Data Science Topic.ipynb
        text: Introduction
      - href: data gathering.ipynb
        text: Data Gathering
      - href: data cleaning.ipynb
        text: Data Cleaning
      - href: eda.ipynb
        text: Data Exploration
      - href: Naïve Bayes.ipynb
        text: Naïve Bayes
      - href: Dimensionality reduction.ipynb
        text: Dimensionality reduction
      - href: Clustering.ipynb
        text: Clustering
      - href: Decision Tree.ipynb
        text: Decision Tree
      - href: Conclusion
        text: Conclusion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



