project:
  type: website

website:
  title: "5000 Homework 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About me
      - href: Data Science Topic.ipynb
        text: Data Science Topic
      - href: data gathering.ipynb
        text: Data Gathering
      - href: data cleaning.ipynb
        text: Data Cleaning
      - href: Naïve Bayes.ipynb
        text: Naïve Bayes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



